services:
  minecraft-one:
    container_name: OneBlock
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      MOTD: "Welcome to LohCraft 1 Block!"
      ICON: "https://i.imgur.com/L3pjNKN.png"
      TZ: "America/Los_Angeles"
      MODRINTH_PROJECTS: |-
        multiverse-core
        aoneblock
      MODRINTH_LOADER: "bukkit"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - minecraft-one:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  minecraft-one: {}
