services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    ports:
      - "25565:25565"
      - "19133:19132/udp"
    volumes:
      - mc_data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  bedrockconnect:
    container_name: bedrockconnect
    image: pugmatt/bedrock-connect
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    environment:
      FEATURED_SERVERS: "true"
      USER_SERVERS: "true"
      CUSTOM_SERVERS: "/brc/custom_servers.json"
    volumes:
      - brc_data:/brc
      - ./custom_servers.json:/brc/custom_servers.json:ro
  dns:
    container_name: bedrockconnect-dns
    image: ubuntu/bind9:9.16-20.04_beta
    restart: unless-stopped
    ports:
      - "0.0.0.0:53:53/udp"
      - "0.0.0.0:53:53/tcp"
    volumes:
      - ./bind9:/etc/bind
    command: ["named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]
volumes:
  mc_data: {}
  brc_data: {}