services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    ports:
      - "25565:25565"
      - "19133:19132/udp"
    volumes:
      - /data/minecraft/mc:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  
  dns-init:
    image: alpine:latest
    volumes:
      - bind_config:/etc/bind
      - ./bind9:/source
    command: >
      sh -c "
        echo 'Copying DNS configuration files...'
        cp -r /source/* /etc/bind/
        chmod -R 644 /etc/bind/*
        echo 'DNS configuration copied successfully'
      "
  
  bedrockconnect:
    container_name: bedrockconnect
    image: pugmatt/bedrock-connect
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    environment:
      FEATURED_SERVERS: "true"
      USER_SERVERS: "true"
      CUSTOM_SERVERS: "/brc/custom_servers.json"
    volumes:
      - /data/minecraft/brc:/brc
      - /data/minecraft/brc/custom_servers.json:/brc/custom_servers.json:ro
  
  dns:
    container_name: bedrockconnect-dns
    image: ubuntu/bind9:9.16-20.04_beta
    restart: unless-stopped
    network_mode: host
    depends_on:
      - dns-init
    volumes:
      - bind_config:/etc/bind
    command: ["named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]

volumes:
  bind_config: {}